### ISSUE TITLE
error in samples on windows

### ISSUE THREAD

**Issue by dsisnero** [SciRuby/rubex#29]
I tried the samples and I keep getting errors like this:

c_struct_interface.rb:1:in `require_relative': no super class for `Music' (ArgumentError)
        from c_struct_interface.rb:1:in `<main>'

I get the same kind of error for all the samples

c:\Dominic\programming\repos\git\rubex\examples\c_struct_interface>ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

**Comment by v0dro** [comment]
Will have a look soon.

**Comment by dsisnero** [comment]
any progress on windows support?

**Comment by v0dro** [comment]
We're currently refactoring the code. Can you have a look and see why this is happening? The current code base runs fine on linux and mac. We don't have any maintainers who use Windows regularly.
