### ISSUE TITLE
Error when using rubex from command line

### ISSUE THREAD

**Issue by v0dro** [SciRuby/rubex#46]
There is a runtime error if using Rubex from the command line after installation.

Here's the error:
```
➜  ~ git:(master) rubex no_gil.rubex 
/home/sameer/.rvm/gems/ruby-2.3.3/gems/rubex-0.1.1/lib/rubex/constants.rb:19:in `<module:Rubex>': uninitialized constant Rubex::DataType::Char (NameError)
	from /home/sameer/.rvm/gems/ruby-2.3.3/gems/rubex-0.1.1/lib/rubex/constants.rb:1:in `<top (required)>'
	from /home/sameer/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/sameer/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/sameer/.rvm/gems/ruby-2.3.3/gems/rubex-0.1.1/lib/rubex.rb:3:in `<top (required)>'
	from /home/sameer/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/sameer/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/sameer/.rvm/gems/ruby-2.3.3/gems/rubex-0.1.1/bin/rubex:3:in `<top (required)>'
	from /home/sameer/.rvm/gems/ruby-2.3.3/bin/rubex:23:in `load'
	from /home/sameer/.rvm/gems/ruby-2.3.3/bin/rubex:23:in `<main>'
	from /home/sameer/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/sameer/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by shaunakpp** [comment]
I'll have a look this weekend, hopefully, sooner!

**Comment by shaunakpp** [comment]
Ah! I think I've figured it out. Are you, by any chance, `cd` ing into the `spec/fixtures/no_gil` directory and *then* running `rubex no_gil.rubex`?

**Comment by v0dro** [comment]
No. The file is in the home directory `~/`.

**Comment by shaunakpp** [comment]
Got it. #56 should fix the issue

**Comment by shaunakpp** [comment]
So, I found some interesting bits when fixing this issue. 
I was using `pry` heavily for debugging this issue and whenever I did `binding.pry` and then called `Dir.pwd` it used to show me the directory from where I've called `rubex no_gil.rubex` and not the directory of the file where `binding.pry` was written.

This led to me scratching my head for couple of hours before understanding that inorder to have context relative to the file I've written `binding.pry` I need to wrap it in `Dir.chdir`
~~~ruby
Dir.chdir(File.dirname(File.dirname(__FILE__))) do
  binding.pry
end
~~~
